import { describe, expect, it } from 'vitest';
import * as primitives from '../../../../src/application/primitives/index.js';

describe('primitives barrel', () => {
  describe('Given the barrel', () => {
    describe('When imported', () => {
      it('Then all primitives are exposed as functions', () => {
        // Arrange
        const names = [
          'appendReflog',
          'applyChangeset',
          'applyConfigOpInText',
          'buildIndexFromTree',
          'buildPack',
          'catFileBatch',
          'computeChangeset',
          'createCommit',
          'deleteReflog',
          'diffTrees',
          'enumeratePushObjects',
          'enumerateRefs',
          'fetchPack',
          'getAllConfigValues',
          'getConfigValue',
          'getRepoRoot',
          'hashBlob',
          'invalidateConfigCache',
          'invalidateScopedConfigCache',
          'isIgnored',
          'isWorkingTreeDirty',
          'listReflogs',
          'loadSparseMatcher',
          'materializeTree',
          'mergeBase',
          'parseIniSections',
          'readBlob',
          'readConfig',
          'readConfigSections',
          'readIndex',
          'readObject',
          'readReflog',
          'readShallow',
          'readSparsePatternText',
          'readTree',
          'recordRefUpdate',
          'reflogExists',
          'resolveRef',
          'resolveReflogIdentity',
          'runHook',
          'setConfigEntryInText',
          'setCoreConfigEntryInText',
          'setEntryFlags',
          'sparseCheckoutPath',
          'stageEntry',
          'synthesizeTreeFromIndex',
          'unstageEntry',
          'updateConfigEntries',
          'updateCoreConfig',
          'updateRef',
          'updateShallow',
          'walkCommits',
          'walkSubmodules',
          'walkTree',
          'walkWorkingTree',
          'writeObject',
          'writeReflog',
          'writeSparsePatternText',
          'writeSymbolicRef',
          'writeTree',
        ];
        for (const name of names) {
          // Assert
          expect(typeof (primitives as Record<string, unknown>)[name]).toBe('function');
        }
      });
    });
    describe('When inspecting keys', () => {
      it('Then only expected public surface is exposed', () => {
        // Arrange
        const expected = new Set([
          'appendReflog',
          'applyChangeset',
          'applyConfigOpInText',
          'buildIndexFromTree',
          'buildPack',
          'catFileBatch',
          'computeChangeset',
          'createCommit',
          'deleteReflog',
          'diffTrees',
          'enumeratePushObjects',
          'enumerateRefs',
          'fetchPack',
          'getAllConfigValues',
          'getConfigValue',
          'getRepoRoot',
          'hashBlob',
          'invalidateConfigCache',
          'invalidateScopedConfigCache',
          'isIgnored',
          'isWorkingTreeDirty',
          'listReflogs',
          'loadSparseMatcher',
          'materializeTree',
          'MAX_SPARSE_PATTERN_FILE_BYTES',
          'mergeBase',
          'parseIniSections',
          'readBlob',
          'readConfig',
          'readConfigSections',
          'readIndex',
          'readObject',
          'readReflog',
          'readShallow',
          'readSparsePatternText',
          'readTree',
          'recordRefUpdate',
          'reflogExists',
          'resolveRef',
          'resolveReflogIdentity',
          'runHook',
          'setConfigEntryInText',
          'setCoreConfigEntryInText',
          'setEntryFlags',
          'sparseCheckoutPath',
          'stageEntry',
          'synthesizeTreeFromIndex',
          'unstageEntry',
          'updateConfigEntries',
          'updateCoreConfig',
          'updateRef',
          'updateShallow',
          'walkCommits',
          'walkSubmodules',
          'walkTree',
          'walkWorkingTree',
          'writeObject',
          'writeReflog',
          'writeSparsePatternText',
          'writeSymbolicRef',
          'writeTree',
        ]);
        const actual = new Set(Object.keys(primitives));
        // Assert
        expect(actual).toEqual(expected);
      });
    });
  });
});
