export type { ConfigKey, ConfigScope, ParsedConfigKey } from './config-key.js';
export type { CommandError } from './error.js';
export {
  authorUnconfigured,
  blockedHost,
  branchExists,
  branchNotFound,
  cannotDeleteCheckedOutBranch,
  checkoutOverwriteDirty,
  configKeyInvalid,
  configMultipleValues,
  configScopeNotAvailable,
  configSectionNotFound,
  configSystemPathUnresolved,
  configValueInvalid,
  emptyCommitMessage,
  emptyPathspec,
  invalidUrl,
  maxRefspecsExceeded,
  mergeHasConflicts,
  nonFastForward,
  noOperationInProgress,
  noPromisorRemote,
  nothingToCommit,
  operationInProgress,
  pathspecNoMatch,
  pathspecOutsideRepo,
  pushRejected,
  remoteAdvertisesNoRefs,
  remoteExists,
  remoteNameInvalid,
  remoteNotConfigured,
  revparseAmbiguous,
  revparseUnresolved,
  sanitize,
  tagExists,
  tagNotFound,
  targetDirectoryNotEmpty,
  tooManyRedirects,
  unsupportedScheme,
  workingTreeDirty,
} from './error.js';
